version: "3.9"
services:
  backend:
    image: registry.null.care/todo-api:latest
    ports:
      - "8000:8000"
    container_name: todo-api
    depends_on:
      - redis-stack
    environment:
      - REDIS_URL=redis://redis/
    networks:
      - todo-network
  redis-stack:
    image: redis/redis-stack:edge
    ports:
      - "8001:8001"
    container_name: redis
    networks:
      - todo-network
    environment:
      - "REDIS_ARGS=--appendonly yes"
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  client:
    image: registry.null.care/todo-client:latest
    command: node --experimental-modules index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 9494:3000
    container_name: todo-client
    environment:
      - VITE_PUBLIC_BASE_PATH=http://backend:8000
    networks:
      - todo-network
    restart: unless-stopped
volumes:
    redis_data:
networks:
  todo-network:
      driver: bridge
