version: "3.9"
services:
  todo-api:
    build: 
      context: todo-api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - redis-stack
    environment:
      - REDIS_URL=redis://redis/
    networks:
      - todo-network
  redis-stack:
    image: redis/redis-stack:edge
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis
    networks:
      - todo-network
    environment:
      - "REDIS_ARGS=--appendonly yes"
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  todo-client:
    restart: unless-stopped
    build: 
      context: todo-client/
      dockerfile: Dockerfile
    command: node --experimental-modules index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 9494:3000
    environment:
      - VITE_PUBLIC_BASE_PATH=http://backend:8000
    networks:
      - todo-network
volumes:
    redis_data:
networks:
  todo-network:
      driver: bridge
