version: "3.8"
services:
  todo-api:
    build: 
      context: todo-api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - redis-stack
    environment:
      - REDIS_URL=redis://redis/
    networks:
      - todo-network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    container_name: redis
    networks:
      - todo-network
  todo-client:
    restart: unless-stopped
    build: 
      context: todo-client/
      dockerfile: Dockerfile
    command: node --experimental-modules index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 9494:3000
    environment:
      - VITE_PUBLIC_BASE_PATH=http://backend:8000
    networks:
      - todo-network
  
networks:
  todo-network:
      driver: bridge